version: "3.9" 

services:
  voucher:
    build: ./frontend
    restart: always
    depends_on:
      - "voucher_backend"
    environment:
      - PUBLIC_HOST=$VOUCHER_URL
      - VIRTUAL_HOST=$VOUCHER_URL
      - LETSENCRYPT_HOST=$VOUCHER_URL
      - VUE_APP_API_URL=$VOUCHER_BACKEND_URL
      - VUE_APP_API_TIMEOUT=200
      - VUE_APP_MOBILE_SKETCH=900
      - VUE_APP_NETWORK=testnet
      - VUE_APP_NETWORK_MATICMUM_SUPPORT=1
      - VUE_APP_NETWORK_POLYGON_MAINNET_SUPPORT=1
  voucher_backend:
    build: ./backend
    restart: always
    ports:
      - 9998:9998
    environment:
      - PUBLIC_HOST=$VOUCHER_BACKEND_URL
      - VIRTUAL_HOST=$VOUCHER_BACKEND_URL
      - LETSENCRYPT_HOST=$VOUCHER_BACKEND_URL
      - OWNER_PK=""
      - PASSWORD_ENV=""
  nginx_cert:
    image: nginxproxy/nginx-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/nginx/certs
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./infra/conf.d:/etc/nginx/conf.d
  acme:
    image: nginxproxy/acme-companion
    restart: always
    volumes_from:
      - nginx_cert
    volumes:
      - /etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - "voucher"
      - "voucher_backend"
